Add support for LCS
redis/redis-py pull request #1866
Opened 2022-01-06 10:20 UTC by dvora-h

### Pull Request check-list

_Please make sure to review and check all of these items:_

- [ ] Does `$ tox` pass with this change (including linting)?
- [ ] Do the CI tests pass with this change (enable it first in your forked repo and wait for the github action build to finish)?
- [ ] Is the new or changed code fully tested?
- [ ] Is a documentation update included (if this change modifies existing APIs, or introduces new ones)?
- [ ] Is there an example added to the examples folder (if applicable)?

_NOTE: these things are not required to open a PR and can be done
afterwards / while the PR is open._

### Description of change

closes #1810

2022-01-12 09:13 UTC, chayim commented on redis/commands/core.py
> +    def lcs(self, key1, key2, len=False, idx=False, minmatchlen=0, withmatchlen=False):
Can we add type hints?

2022-01-12 09:13 UTC, chayim requested changes
Let's start getting type hints into our commands...

2022-01-27 08:31 UTC, chayim commented
@dvora-h Can you reseed this or make a new PR on master. 35 changes is... too many.

2022-02-02 12:13 UTC, dvora-h commented
Done in #1924

2022-02-02 12:13 UTC, closed without merging