`Retry()`: Support negative `retries` value
redis/redis-py pull request #2110
Opened 2022-04-15 10:26 UTC by kristjanvalur

### Pull Request check-list

- [x] Does `$ tox` pass with this change (including linting)?
- [x] Do the CI tests pass with this change (enable it first in your forked repo and wait for the github action build to finish)?
- [x] Is the new or changed code fully tested?
- [x] Is a documentation update included (if this change modifies existing APIs, or introduces new ones)?
- [ ] Is there an example added to the examples folder (if applicable)?
- [x] Was the change added to CHANGES file?

### Description of change

The `Retry` class now accepts a negative value for `retries` indicating no upper limit on the number of retries; the action
will be retried until it succeeds.

2022-04-21 19:03 UTC, WisdomPill requested changes
It seems to me that sync version tests are missing

2022-04-23 09:08 UTC, WisdomPill commented
did you break `pypy-3.7 standalone-hiredis tests`?

2022-04-23 09:09 UTC, WisdomPill commented
can you rebase? maybe that's the reason why the CI is broken

2022-04-24 14:20 UTC, WisdomPill approved these changes
LGTM! 

maybe good old @chayim should have another look here since I am quite new into reviewing PRs in this repo

2022-04-24 14:24 UTC, chayim commented
This looks like a red herring. I expect the python 3.11a builds to fail (hence, they don't break CI). But - the change looks innocuous enough. I suspect it triggered something else. Re-running the action.

2022-04-24 14:39 UTC, chayim approved these changes

2022-04-24 14:40 UTC, WisdomPill commented
@chayim nice catch! :)

2022-04-25 09:05 UTC, kristjanvalur commented
Yes, pretty sure nothing in the change was causing these builder issues.

2022-04-28 11:16 UTC, merged