Replace OSError exceptions from `can_read` with `redis.ConnectionError`
redis/redis-py pull request #2140
Opened 2022-04-25 14:58 UTC by kristjanvalur

### Pull Request check-list

_Please make sure to review and check all of these items:_

- [ ] Does `$ tox` pass with this change (including linting)?
- [ ] Do the CI tests pass with this change (enable it first in your forked repo and wait for the github action build to finish)?
- [ ] Is the new or changed code fully tested?
- [ ] Is a documentation update included (if this change modifies existing APIs, or introduces new ones)?
- [ ] Is there an example added to the examples folder (if applicable)?
- [ ] Was the change added to CHANGES file?

_NOTE: these things are not required to open a PR and can be done
afterwards / while the PR is open._

### Description of change

This change catches OS errors in `Connection.can_read`, closes connection and raises a `redis.ConnectionError`.
Fixes #2138

2022-04-27 07:06 UTC, chayim commented
@kristjanvalur I tried to push an update to your branch, to fix the linters. Can you run the following to fix your linting? Then we can merge!

```
black redis
```

2022-04-27 07:06 UTC, chayim commented on redis/asyncio/connection.py
> +                f"Error while reading from {self.host}:{self.port} : {e.args}"
Nice. Small nit to remove a space.
```
                f"Error while reading from {self.host}:{self.port}: {e.args}"
```

2022-04-27 07:06 UTC, chayim commented on redis/connection.py
> +            raise ConnectionError(f"Error while reading from {self.host}:{self.port} : {e.args}")
Same
```
                f"Error while reading from {self.host}:{self.port}: {e.args}"
```

2022-04-27 07:06 UTC, chayim requested changes
Ready to merge pending the lint fix, and this small change!

2022-05-03 11:37 UTC, dvora-h approved these changes

2022-05-08 12:01 UTC, chayim approved these changes

2022-05-08 12:03 UTC, merged