[DOC BUG] Add r=redis.Redis() step to bloom commands
redis/redis-py pull request #2478
Opened 2022-11-29 17:10 UTC by nermiller

Fixes #2415, adds a connect step to bloom commands

2022-11-29 17:23 UTC, savynorem requested changes
@nermiller sorry I didn't articulate this well - the connection will need to be after the import, then the connection name is what needs to be used - also, the return from create is a boolean, it can't actually be used to alter the data structure, so they'll need to be more like
`
import redis
r = redis.Redis()
r.bf().create("bloom", .01, 1000)
r.bf().add("bloom", foo)
`

The return values are pretty much only used as a success / fail / did something change type of measure, they don't return a way to access the object.

2022-11-29 17:38 UTC, nermiller commented
@savynorem please review again. Thanks!

2022-11-29 18:09 UTC, savynorem approved these changes
👍  looks great to me!

2022-11-30 07:40 UTC, chayim approved these changes

2022-11-30 14:30 UTC, merged