Version 4.3.7
redis/redis-py pull request #2672
Opened 2023-03-29 09:53 UTC by dvora-h

### Pull Request check-list

_Please make sure to review and check all of these items:_

- [ ] Does `$ tox` pass with this change (including linting)?
- [ ] Do the CI tests pass with this change (enable it first in your forked repo and wait for the github action build to finish)?
- [ ] Is the new or changed code fully tested?
- [ ] Is a documentation update included (if this change modifies existing APIs, or introduces new ones)?
- [ ] Is there an example added to the examples folder (if applicable)?
- [ ] Was the change added to CHANGES file?

_NOTE: these things are not required to open a PR and can be done
afterwards / while the PR is open._

### Description of change

Closes #2665

2023-03-31 14:47 UTC, jamestiotio requested changes
For Python 3.6, these calls to `asyncio.create_task` should be modified to `asyncio.ensure_future` instead.

EDIT: Seems like `asyncio.CancelledError` existed in [Python 3.6.0's code](https://github.com/python/cpython/blob/v3.6.0/Lib/asyncio/base_futures.py#L9) after all, it was just undocumented (earliest documented page of [asyncio exceptions](https://docs.python.org/3.7/library/asyncio-exceptions.html) was for Python 3.7). Ignore my previous comment about `asyncio.CancelledError`.

2023-03-31 14:47 UTC, jamestiotio commented on tests/test_asyncio/test_cwe_404.py
> +        self.ROUTINE = asyncio.create_task(self.server.serve_forever())
```suggestion
        self.ROUTINE = asyncio.ensure_future(self.server.serve_forever())
```

2023-03-31 14:47 UTC, jamestiotio commented on tests/test_asyncio/test_cwe_404.py
> +        pipe1 = asyncio.create_task(pipe(reader, redis_writer, self.delay, "to redis:"))
```suggestion
        pipe1 = asyncio.ensure_future(pipe(reader, redis_writer, self.delay, "to redis:"))
```

2023-03-31 14:47 UTC, jamestiotio commented on tests/test_asyncio/test_cwe_404.py
> +        pipe2 = asyncio.create_task(
```suggestion
        pipe2 = asyncio.ensure_future(
```

2023-03-31 14:47 UTC, jamestiotio commented on tests/test_asyncio/test_cwe_404.py
> +            t = asyncio.create_task(r.get("foo"))
```suggestion
            t = asyncio.ensure_future(r.get("foo"))
```

2023-03-31 14:47 UTC, jamestiotio commented on tests/test_asyncio/test_cwe_404.py
> +        t = asyncio.create_task(pipe.get("foo").execute())
```suggestion
        t = asyncio.ensure_future(pipe.get("foo").execute())
```

2023-03-31 14:47 UTC, jamestiotio commented on tests/test_asyncio/test_cwe_404.py
> +    t = asyncio.create_task(r.get("foo"))
```suggestion
    t = asyncio.ensure_future(r.get("foo"))
```

2023-03-31 15:51 UTC, auvipy commented
will be looking forward to this release

2023-04-04 10:38 UTC, chayim commented
Using the proxy changes from @drago-balto, combined with the current 4.3 branch yields a sideaffect in this particular case. Given the output errors on RuntimeError - we can now be positive, that the fix is truly caught.

However, the byproduct of that is this given case. If you cancel an executing pipeline (as [in our test](https://github.com/redis/redis-py/pull/2672/files#diff-a90c3a19dad7803c9726358f223a3b7b8fb23ccb1d573d580d6640f04fdd3f27R103) then the pipeline object cannot be reused.

Technically, it's always been possible (and works) to reuse the pipeline object, rather than reinitialize it:

```
r = Redis()
pipe = r.pipeline()
pipe.set("foo", "bar")
pipe.execute()

pipe.set("bar", "blee")
pipe.get("foo")
pipe.execute()
````

However, in 4.3 this won't be possible *should* the async be canceled. IMHO this is reasonable, it's a security fix we're backporting to a dead branch. Meaning if you end up in this situation, you can easily catch RuntimeError and move along.

Thoughts community?

2023-04-16 06:20 UTC, chayim commented
@auvipy I haven't seen feedback from anyone.. I let it bake for two weeks, to make sure there's real interest here. Can you confirm - is there - and does this fix work happily for you?  Anyone else, please feel free to weigh in.

This version is old enough, that I want to double-check here.

2023-04-16 07:59 UTC, auvipy reviewed
at celery we use mostly the sync versions codes so far

2023-04-16 08:00 UTC, auvipy commented
but we are py 3.7+ and pypy 3.8+

2023-04-17 13:11 UTC, chayim commented
Right. Since celery is py 3.7+ this PR isn't needed. That's already covered by existing releases.

@dvora-h Let's let this bake. If no one *needs* the change, specifically due to python 3.6, we abandon.

2023-04-18 04:33 UTC, auvipy commented
but we need to calm down pyup

2023-04-23 09:26 UTC, chayim commented
> but we need to calm down pyup

That sounds like a misconfiguration of pyup and IMHO not a reason to release this. I'd rather not extend a potential issue.

Celery releases clearly support Python 3.7+, especially since 3.6 has been end of lifed.  I went back through the history of the repository and Pypi, and haven't seen an active version support Python 3.6.

This has sat long enough, I think we can close. Thank you everyone who helps us get to this point!

2023-04-23 09:26 UTC, closed without merging