Add support for cluster myshardid
redis/redis-py pull request #2704
Opened 2023-04-11 09:32 UTC by SoulPancake

- fixes #2683

2023-04-14 14:55 UTC, SoulPancake commented
@dvora-h Is the lint issue related to my changes ?
How can I fix it?

2023-04-25 03:04 UTC, XChikuX requested changes
Please take care of linting issues.

2023-04-25 03:04 UTC, XChikuX commented on tests/test_cluster.py
> +                        Connection, send_command=DEFAULT, connect=DEFAULT, can_read=DEFAULT
You should remove these extra spacings. It's making linting fail!!

2023-04-25 03:04 UTC, XChikuX commented on tests/test_cluster.py
> +                str(ex.value).startswith("shard_hint is deprecated in cluster mode") is True
Same here. Consider using a VS code python plugin that can take care of this. Like Sonarlint.

2023-04-27 13:58 UTC, dvora-h requested changes
@SoulPancake The lint issue is, as @XChikuX said, because of the extra spaces you added, you need to remove them.

I also added 2 minor comments, after you fix them, we can merge it.

2023-04-27 13:58 UTC, dvora-h commented on redis/commands/cluster.py
> +        """
Looks like you copied CLUSTER SHARDS comment, can you update to the appropriate comment

2023-04-27 13:58 UTC, dvora-h commented on tests/test_cluster.py
> +    def test_cluster_myshardid(self, r):
Can you add an async version of the test to tests/test_asyncio/test_cluster.py

2023-05-08 07:13 UTC, dvora-h approved these changes

2023-05-08 07:14 UTC, dvora-h commented
@SoulPancake I hope you don't mind I fixed the linters...
I want to merge it and include it in 4.5.5

2023-05-08 07:21 UTC, SoulPancake commented
@dvora-h 
Sorry for not being active here
Is there anything else I need to do here?

2023-05-08 08:01 UTC, dvora-h commented
@SoulPancake No, this is ready now

2023-05-08 08:01 UTC, merged