save a reference to created tasks, to avoid tasks disappearing
redis/redis-py pull request #2816
Opened 2023-06-28 11:11 UTC by anio

> Save a reference to the result of this function, to avoid a task disappearing mid-execution. The event loop only keeps weak references to tasks. A task that isn’t referenced elsewhere may get garbage collected at any time, even before it’s done.
>
> [python docs](https://docs.python.org/3/library/asyncio-task.html#asyncio.create_task)

### Pull Request check-list

_Please make sure to review and check all of these items:_

- [ ] Does `$ tox` pass with this change (including linting)?
- [ ] Do the CI tests pass with this change (enable it first in your forked repo and wait for the github action build to finish)?
- [ ] Is the new or changed code fully tested?
- [ ] Is a documentation update included (if this change modifies existing APIs, or introduces new ones)?
- [ ] Is there an example added to the examples folder (if applicable)?
- [ ] Was the change added to CHANGES file?

_NOTE: these things are not required to open a PR and can be done
afterwards / while the PR is open._

### Description of change

Please review the link: https://textual.textualize.io/blog/2023/02/11/the-heisenbug-lurking-in-your-async-code/

2023-09-20 10:14 UTC, dvora-h requested changes

2023-09-20 10:14 UTC, dvora-h commented on redis/asyncio/cluster.py
> +                    task = asyncio.create_task(old.pop(name).disconnect())
```suggestion
                    task = asyncio.create_task(old.pop(name).disconnect())  # noqa
```

2023-09-20 10:14 UTC, dvora-h commented on redis/asyncio/cluster.py
> +                task = asyncio.create_task(old[name].disconnect())
```suggestion
                task = asyncio.create_task(old[name].disconnect())  # noqa
```

2023-09-20 10:14 UTC, dvora-h commented on redis/asyncio/cluster.py
> +                    task = asyncio.create_task(old.pop(name).disconnect())
Skip linter check

2023-09-20 10:14 UTC, dvora-h commented on redis/asyncio/cluster.py
> +                task = asyncio.create_task(old[name].disconnect())
same

2023-09-21 08:48 UTC, dvora-h approved these changes

2023-09-21 08:48 UTC, merged

2023-09-27 00:33 UTC, jakob-keller commented
@anio: Thanks for bringing the issue up!

I am not convinced that the fix is appropriate, though. As the [source you provide](https://textual.textualize.io/blog/2023/02/11/the-heisenbug-lurking-in-your-async-code/) mentions:

> The solution recommended in the docs is to keep a reference to the task for as long as you need it to live.

The way I understand it is, that we need to save the task reference beyond the scope of the local / loop variable. As it stands, the reference will be lost almost immediately, rendering the fix ineffective.