Create dt_list.py
redis/redis-py pull request #2855
Opened 2023-07-18 16:29 UTC by sav-norem

add the data type list python code for tabbed examples

### Pull Request check-list

_Please make sure to review and check all of these items:_

- [ ] Does `$ tox` pass with this change (including linting)?
- [ ] Do the CI tests pass with this change (enable it first in your forked repo and wait for the github action build to finish)?
- [ ] Is the new or changed code fully tested?
- [ ] Is a documentation update included (if this change modifies existing APIs, or introduces new ones)?
- [ ] Is there an example added to the examples folder (if applicable)?
- [ ] Was the change added to CHANGES file?

_NOTE: these things are not required to open a PR and can be done
afterwards / while the PR is open._

### Description of change

_Please provide a description of the change here._

2023-07-18 16:29 UTC, sav-norem commented
@uglide and lists!

2023-07-20 12:31 UTC, uglide requested changes
Great work!
We can make this example more concise by explaining List basics around one pattern Producer/Consumer which is extensively covered in the current version of the doc here https://redis.io/docs/data-types/lists/

2023-07-20 12:31 UTC, uglide commented on doctests/dt_list.py
> +r.delete("bikes:repairs")
Please wrap those two lines in the REMOVE_START/END block to hide this cleanup code from the users.

2023-07-20 12:31 UTC, uglide commented on doctests/dt_list.py
> +# STEP_START queue
See my comment here https://github.com/redis/redis-doc/pull/2488/files#r1269382572

2023-07-25 17:07 UTC, sav-norem commented
@uglide I believe those changes would be better addressed with an issue for the docs team to rework the structure of that content

2023-09-11 17:27 UTC, sav-norem commented
@chayim if you could take a look!

2023-09-12 12:18 UTC, merged