Switch to PEP 517 packaging using hatchling
redis/redis-py pull request #2930
Opened 2023-09-04 10:23 UTC by akx

### Pull Request check-list

_Please make sure to review and check all of these items:_

- [ ] Does `$ tox` pass with this change (including linting)?
  - No, Tox hasn't passed since #2849 was merged. See #2929. 
- [ ] Do the CI tests pass with this change (enable it first in your forked repo and wait for the github action build to finish)?
- [ ] Is the new or changed code fully tested?
- [ ] Is a documentation update included (if this change modifies existing APIs, or introduces new ones)?
- [ ] Is there an example added to the examples folder (if applicable)?
- [ ] Was the change added to CHANGES file?

### Description of change

* Refs #1316
* Refs #1649
* ♻️ Remake of #2388, a year later
*❗Contains dependency changes from #2928 

Quoting the description from #2388...

This PR shifts redis-py from legacy `setup.py` packaging to [PEP 517](https://peps.python.org/pep-0517/) compliant packaging [using `hatchling` from PyPA](https://hatch.pypa.io/latest/).

Essentially, this does what was discussed in #1658 but with the increasingly standard `hatchling` tool instead of poetry's idiosyncracies.

As with #2388, `python -m build` does create a working wheel with all modules included.

2024-06-12 06:13 UTC, akx commented
Rebased.

2024-08-27 09:40 UTC, akx commented
Rebased. Cc @gerzse @vladvildanov.

2024-09-02 11:50 UTC, vladvildanov commented
@akx Thanks for your contribution! I'll review this PR in near time

2024-10-16 05:53 UTC, akx commented
@vladvildanov Good to hear. Rebased once again.

2024-10-16 06:37 UTC, vladvildanov requested changes

2024-10-16 06:37 UTC, vladvildanov commented on redis/__init__.py
> +__version__ = "5.1.0b7"
Should be changed to 5.1.1

2025-02-20 10:59 UTC, akx commented
@vladvildanov Rebased.

2025-02-21 06:50 UTC, akx commented
Btw: the tests failing in

```
FAILED tests/test_asyncio/test_commands.py::TestRedisCommands::test_client_setinfo[single] - AssertionError: assert '5.3.0b5' == '5.2.1'
    
    - 5.2.1
    + 5.3.0b5
```

is _very_ curious – given the string "5.3.0b5" does not appear in the source here at all, it almost looks like the CI pipeline is installing an entirely different version of the package...

and indeed:

```
  Downloading redis-5.3.0b5-py3-none-any.whl (271 kB)
```

IOW, the CI pipeline seems to be confused about which libraries it's using...

2025-02-24 12:40 UTC, petyaslavova commented on tasks.py
> -    run("python setup.py sdist bdist_wheel")
You need to add 'build' dependency to the dev_requirements.txt - its existence in Python is not guaranteed. For example, in my new virtual environment, it wasn't installed...

2025-02-24 12:40 UTC, petyaslavova commented on .github/actions/run-tests/action.yml
>          pip install -r requirements.txt
Do we still need to support the requirements.txt file? In the README.md the dependency installation section states that we should install the dependencies using the command "pip install -e ." . In this case the information in requirements.txt and pyproject.toml becomes redundant.

2025-02-24 12:40 UTC, petyaslavova commented on .github/actions/run-tests/action.yml
>          pip install -U setuptools wheel
wheel is already part of the dev_requirements dependencies, and since you are adding hatchling as build backend, probably setuptools is also not needed. Would you please check if this dependency installation can also be skipped?

2025-02-25 07:54 UTC, akx commented on pyproject.toml
> +    'async-timeout>=4.0.3; python_full_version<"3.11.3"',
Each dependency here is on a single line.

`; python_full_version<"3.11.3"` is a marker that specifies that this requirement should only be installed in an environment where this marker is fulfilled.

This is the same as it is in current `master`:

https://github.com/redis/redis-py/blob/d8676605ef05c786bb705257467a83f963cd1d04/setup.py#L40

See https://github.com/redis/redis-py/issues/3174 for discussion about why the marker is added.

2025-02-25 07:57 UTC, akx commented on tasks.py
> -    run("python setup.py sdist bdist_wheel")
[`build`](https://pypi.org/project/build/) isn't the only PEP517 build frontend – one could use, for instance, `uv build` instead. But sure, I'll add that.

2025-02-25 08:00 UTC, akx commented on .github/actions/run-tests/action.yml
>          pip install -U setuptools wheel
It's unlikely that `wheel` is required either.

> **Historical note**
> This project used to contain the implementation of the setuptools bdist_wheel command, but as of setuptools v70.1, it no longer needs wheel installed for that to work. Thus, you should install this only if you intend to use the wheel command line tool!

– https://pypi.org/project/wheel/

2025-02-25 08:21 UTC, petyaslavova commented on pyproject.toml
> +include = [
Can you please add tests, pytest.ini and dev_requirements.txt in the built package. These items exist in the current package.

2025-02-25 08:49 UTC, akx commented on pyproject.toml
> +include = [
Sure.

* Moved [pytest configuration to pyproject.toml](https://docs.pytest.org/en/stable/reference/customize.html#pyproject-toml) so the INI file isn't needed.
* Added tests and dev_requirements to the sdist targets.

I compared the dists built from `master` and this PR and aside from some expected changes, they're identical.

<img width="1358" alt="Screenshot 2025-02-25 at 10 48 44" src="https://github.com/user-attachments/assets/cab6ea10-4351-40fe-b460-be9f3f9b612d" />

2025-02-25 09:38 UTC, petyaslavova approved these changes
LGTM

2025-02-25 10:55 UTC, vladvildanov approved these changes

2025-02-25 10:58 UTC, merged

2025-02-25 11:17 UTC, akx commented
Thanks for getting this finally merged!

1 year, 5 months 3 weeks – could easily be a personal record for PR perseverance for me.

2025-02-25 13:11 UTC, vladvildanov commented
@akx Thanks for your efforts, I'm so sorry that It took so long from our side