Client Side Caching
redis/redis-py pull request #3038
Opened 2023-11-13 01:02 UTC by dvora-h

### Pull Request check-list

_Please make sure to review and check all of these items:_

- [ ] Do tests and lints pass with this change?
- [ ] Do the CI tests pass with this change (enable it first in your forked repo and wait for the github action build to finish)?
- [ ] Is the new or changed code fully tested?
- [ ] Is a documentation update included (if this change modifies existing APIs, or introduces new ones)?
- [ ] Is there an example added to the examples folder (if applicable)?
- [ ] Was the change added to CHANGES file?

_NOTE: these things are not required to open a PR and can be done
afterwards / while the PR is open._

### Description of change

_Please provide a description of the change here._

2023-11-14 09:38 UTC, chayim commented on redis/cache.py
> +class _Cache:
docstrings + documentation help

2023-11-14 09:43 UTC, chayim commented on redis/client.py
> +        client_cache: Optional[_Cache] = None,
Can we pull the default string values (lru) into the cache.py also? DEFAULT_EVICTION_POLICY

2023-11-14 09:44 UTC, chayim commented on redis/client.py
> +        self.cache_blacklist = cache_blacklist
Shouldn't all these values be set only if client_cache is true? I'd assume blacklist/whitelist to be empty, when False, we can save the memory, at the very least.

2023-11-14 09:44 UTC, chayim commented on redis/client.py
> +    def get_from_local_cache(self, command):
docstring, type hint
`_get_from_local_cache`

2023-11-14 09:45 UTC, chayim commented on redis/client.py
> +    def add_to_local_cache(self, command, response, keys):
docstring, type hint
`_add_to_local_cache`

2023-11-14 09:46 UTC, chayim commented on redis/client.py
> +    def delete_from_local_cache(self, command):
docstring, type hint
`_delete_from_local_cache_`

2023-11-14 09:46 UTC, chayim commented on redis/client.py
> +            self.client_cache.delete(command)
Is it cheaper to attempt a deletion whether or not the field exists - and just trigger the delete?

2023-11-14 09:47 UTC, chayim commented on redis/utils.py
> +DEFAULT_BLACKLIST = [
I think it makes more sense for this to live in cache.py

2023-11-14 09:47 UTC, chayim commented on redis/utils.py
> +DEFAULT_BLACKLIST = [
Also, let's sort

2023-11-14 09:54 UTC, chayim commented on redis/cache.py
> +        self.eviction_policy = eviction_policy
We should have a list of policies mapped in this class. Then, map them to [enum](https://docs.python.org/3/library/enum.html) to make to make it available during configuration

2023-11-14 09:55 UTC, chayim commented on redis/cache.py
> +    def set(self, command, response, keys_in_command):
type hints, docstrings, etc

2023-11-14 09:55 UTC, chayim commented on redis/cache.py
> +            "created_time": time.monotonic(),
`created_time` -> `ctime`? Smaller use, and ctime is accepted as created_time

2023-11-14 09:55 UTC, chayim commented on redis/cache.py
> +        if self.eviction_policy == "lfu":
should refer to the enum

2023-11-14 09:55 UTC, chayim commented on redis/cache.py
> +            self.cache[command]["access_count"] = 0
Let's declare all fields and reuse

2023-11-14 09:56 UTC, chayim commented on redis/cache.py
> +    def get(self, command):
type hints, docstrings -> etc. let's just say for all functions

2023-11-14 09:56 UTC, chayim commented on redis/cache.py
> +                self._del_key_commands_map(keys_in_command, command)
self.cache[command].get("keys") for future thread-safe use, and not worrying about `IndexError`

2023-11-14 09:57 UTC, chayim commented on redis/cache.py
> +                return None
None is implied, can just use `return`

2023-11-14 09:57 UTC, chayim commented on redis/cache.py
> +        return None
None is implied, can just use `return`

2023-11-14 09:57 UTC, chayim commented on redis/cache.py
> +        elif self.eviction_policy == "lfu":
enum

2023-11-14 09:58 UTC, chayim commented on redis/cache.py
> +            for command in self.key_commands_map[key]:
How have if not in map return, then run the for, next?

2023-11-14 09:59 UTC, chayim commented on redis/cache.py
> +            self.key_commands_map[key].add(command)
Can we `self.key_commands_map[key] += command` or did I not understand what command is here?

2023-11-14 10:04 UTC, chayim commented on redis/cache.py
> +    def _del_key_commands_map(self, keys, command):
Take a look at [itertools.filterfalse](https://docs.python.org/3.8/library/itertools.html#itertools.filterfalse), might be useful.

2023-11-14 10:05 UTC, chayim requested changes
@dvora-h see comments

2023-11-16 07:53 UTC, chayim commented on redis/asyncio/client.py
> +        options.pop("keys", None)  # the keys is used only for client side caching
"the keys are used only for client side caching

2023-11-16 07:53 UTC, chayim commented on redis/cache.py
> +import random
To keep in theme we discussed, maybe this should be redis.cache.LocalCache?

2023-11-16 07:53 UTC, chayim commented on redis/cache.py
> +class EvictionPolicy(Enum):
awesome

2023-11-16 10:26 UTC, merged

2023-11-16 15:56 UTC, rueian commented
Wow, this is cool. Will the client tracking be supported in this client cache?

2023-11-17 00:25 UTC, rueian commented
> @rueian Yes, we are going to add it, this is why it's just an alpha version now I hope the next version will come soon with client tracking

Great! Can’t wait to see this powerful feature be available on redis py. This will definitely gain more acknowledgment on this feature from more developers.