skip `ssl` import if not available
redis/redis-py pull request #3078
Opened 2023-12-18 17:50 UTC by dicej

### Pull Request check-list

_Please make sure to review and check all of these items:_

- [x] Do tests and lints pass with this change?
- [ ] Do the CI tests pass with this change (enable it first in your forked repo and wait for the github action build to finish)?
- [ ] Is the new or changed code fully tested?
- [ ] Is a documentation update included (if this change modifies existing APIs, or introduces new ones)?
- [ ] Is there an example added to the examples folder (if applicable)?
- [x] Was the change added to CHANGES file?

_NOTE: these things are not required to open a PR and can be done
afterwards / while the PR is open._

### Description of change

`utils.py` has support for detecting whether the `ssl` module is available, and we can use this to omit SSL-specific funcionality while still providing other features (e.g. unencrypted connections).

Prior to this patch, the `connection.py` modules both triggered an `ImportError` due to unconditional imports of the `ssl` module.  Now, we check `utils.SSL_AVAILABLE` prior to attempting the import and only raise an error later if (and only if) the application requests an encrypted connection.  This helps support platforms such as `wasm32-wasi` where the `ssl` module is not built by default.

Ideally, this would be tested in CI using a Python built without `ssl` support.  I'm not sure how feasible that is, though; I'm open to guidance on that aspect.

2025-03-10 10:50 UTC, petyaslavova commented
Hi @dicej, can you please update your code to follow the pattern set in https://github.com/redis/redis-py/blob/master/redis/client.py for ssl import and type hints and fix the conflicts?

2025-03-12 23:07 UTC, dicej commented
> Hi @dicej, can you please update your code to follow the pattern set in https://github.com/redis/redis-py/blob/master/redis/client.py for ssl import and type hints and fix the conflicts?

Done, and tested on `wasm32-wasi` (which does not have an `ssl` module).

2025-03-13 08:58 UTC, petyaslavova commented on redis/asyncio/cluster.py
> +    ssl = None
In this case, I don't think you need to import and add any initialization of the ssl. 
In the end, you are using just the TLSVersion, and you can handle just this import and default init in case ssl is not available. The same applies for client and cluster files.

2025-03-13 08:59 UTC, petyaslavova requested changes
@dicej please fix the linter errors and apply requested changes

2025-03-13 17:30 UTC, petyaslavova commented on redis/asyncio/connection.py
> +if TYPE_CHECKING and SSL_AVAILABLE:
It seems that the TYPE_CHECKING test here breaks the import of ssl when it really needs to be imported. Can you please remove it +  the import of TYPE_CHECKING?

2025-03-14 08:16 UTC, petyaslavova approved these changes

2025-03-14 08:16 UTC, merged