typing for client __init__
redis/redis-py pull request #3357
Opened 2024-08-19 12:29 UTC by Vulwsztyn

### Pull Request check-list

_Please make sure to review and check all of these items:_

- [ ] Do tests and lints pass with this change?
- [ ] Do the CI tests pass with this change (enable it first in your forked repo and wait for the github action build to finish)?
- [ ] Is the new or changed code fully tested?
- [ ] Is a documentation update included (if this change modifies existing APIs, or introduces new ones)?
- [ ] Is there an example added to the examples folder (if applicable)?
- [ ] Was the change added to CHANGES file?

_NOTE: these things are not required to open a PR and can be done
afterwards / while the PR is open._

### Description of change

_Please provide a description of the change here._

2024-09-04 08:48 UTC, vladvildanov commented
@Vulwsztyn Tests are failing, cause of conditional OpenSSL dependency

2024-09-04 08:49 UTC, Vulwsztyn commented
@vladvildanov thanks I'll make it unconditional

2024-09-04 08:51 UTC, vladvildanov commented
@Vulwsztyn Thank you for your contribution!

2024-09-04 09:23 UTC, Vulwsztyn commented
@vladvildanov I changed the typing to string literals so that it doesn't require imports and removed the conditional imports

2024-09-08 22:31 UTC, Vulwsztyn commented
@vladvildanov Any insight as to why the tests are failing now? Should I do something?

2024-09-11 16:09 UTC, Vulwsztyn commented
@vladvildanov I fixed the linters. Sorry it took so long.

```
> invoke linters
All done! ✨ 🍰 ✨
134 files would be left unchanged.
Running flynt v.0.69
Running flynt in dry-run mode. No files will be changed.

Flynt run has finished. Stats:

Execution time:                            2.488s
Files modified:                            0

_-_._-_._-_._-_._-_._-_._-_._-_._-_._-_._-_._-_._-_._-_._-_._-_._-_._-_._-_._-_._-_._-_._-_._-_._-_.
Please run your tests before committing. Did flynt get a perfect conversion? give it a star at: 
~ https://github.com/ikamensh/flynt ~
Thank you for using flynt. Upgrade more projects and recommend it to your colleagues!
> invoke linters
All done! ✨ 🍰 ✨
134 files would be left unchanged.
Running flynt v.0.69
Running flynt in dry-run mode. No files will be changed.

Flynt run has finished. Stats:

Execution time:                            2.488s
Files modified:                            0

_-_._-_._-_._-_._-_._-_._-_._-_._-_._-_._-_._-_._-_._-_._-_._-_._-_._-_._-_._-_._-_._-_._-_._-_._-_.
Please run your tests before committing. Did flynt get a perfect conversion? give it a star at: 
~ https://github.com/ikamensh/flynt ~
Thank you for using flynt. Upgrade more projects and recommend it to your colleagues!
```

2024-09-14 12:20 UTC, Vulwsztyn commented
rebased unto master

2024-09-19 08:26 UTC, vladvildanov commented
@Vulwsztyn OpenSSL is still an issue if you have a look in CI logs

2024-09-19 10:32 UTC, Vulwsztyn commented
@vladvildanov Thanks for the ping.

I don't get something here. In this line https://github.com/redis/redis-py/blob/7d73d742d6df4b3d6f6a1f0ec73e72d4a02add74/redis/connection.py#L870 in this project we `import OpenSSL`, but it is not a dependency of this project? Should it remain so?

2024-09-19 12:43 UTC, vladvildanov commented
@Vulwsztyn https://redis-py.readthedocs.io/en/stable/examples/ssl_connection_examples.html#Connect-via-SSL,-validate-OCSP-stapled-certificates

2024-09-20 17:23 UTC, Vulwsztyn commented
Removed the typing requiring openssl

2024-11-12 15:47 UTC, Vulwsztyn commented
Could you try running the tests please?

2025-01-21 09:13 UTC, vladvildanov requested changes

2025-01-21 09:13 UTC, vladvildanov commented on redis/client.py
> +        retry: Union[Any, None] = None,
Should be `retry: Optional[Retry] = None`

2025-01-21 17:08 UTC, Vulwsztyn commented on redis/client.py
> +        retry: Union[Any, None] = None,
Addressed, thank you

2025-02-04 12:15 UTC, patrick91 commented on redis/client.py
> +        retry_on_error: Optional[list] = None,
I'd make this `Optional[List[Any]]` just to be more explicit (and to prevent issues in more strict type checking configurations)

Also, I think it is a list of exception types, so we can do:

 `Optional[List[Type[Exception]]]` or maybe  `Optional[List[Type[RedisError]]]` 😊

2025-02-04 12:30 UTC, Vulwsztyn commented on redis/client.py
> +        retry_on_error: Optional[list] = None,
Done

2025-02-05 13:29 UTC, Vulwsztyn commented
I refixed lint

2025-02-07 11:59 UTC, Vulwsztyn commented
I see that all checks are passing. Would it be possible to merge this?

2025-02-10 08:39 UTC, vladvildanov commented
@Vulwsztyn waiting for checks after latest sync with master and good to go

2025-02-10 14:56 UTC, merged