Avoid the multiprocessing forkserver method in Python 3.14
redis/redis-py pull request #3442
Opened 2024-11-26 13:17 UTC by befeleme

### Pull Request check-list

_Please make sure to review and check all of these items:_

- [ ] Do tests and lints pass with this change?
- [ ] Do the CI tests pass with this change (enable it first in your forked repo and wait for the github action build to finish)?
- [ ] Is the new or changed code fully tested?
- [ ] Is a documentation update included (if this change modifies existing APIs, or introduces new ones)?
- [ ] Is there an example added to the examples folder (if applicable)?
- [ ] Was the change added to CHANGES file?

_NOTE: these things are not required to open a PR and can be done
afterwards / while the PR is open._

### Description of change

This change is essentially a copy of: https://github.com/giampaolo/pyftpdlib/pull/656

Python 3.14 has changed the default multiprocessing method from fork to forkserver which causes failures like this one:

```
____________________ TestMultiprocessing.test_redis_client _____________________

self = <tests.test_multiprocessing.TestMultiprocessing object at 0x7f646b43d250>
r = <redis.client.Redis(<redis.connection.ConnectionPool(<redis.connection.Connection(host=localhost,port=6379,db=0)>)>)>

    def test_redis_client(self, r):
        "A redis client created in a parent can also be used in a child"
        assert r.ping() is True
    
        def target(client):
            assert client.ping() is True
            del client
    
        proc = multiprocessing.Process(target=target, args=(r,))
>       proc.start()

tests/test_multiprocessing.py:163: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
/usr/lib64/python3.14/multiprocessing/process.py:121: in start
    self._popen = self._Popen(self)
/usr/lib64/python3.14/multiprocessing/context.py:224: in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
/usr/lib64/python3.14/multiprocessing/context.py:300: in _Popen
    return Popen(process_obj)
/usr/lib64/python3.14/multiprocessing/popen_forkserver.py:35: in __init__
    super().__init__(process_obj)
/usr/lib64/python3.14/multiprocessing/popen_fork.py:20: in __init__
    self._launch(process_obj)
/usr/lib64/python3.14/multiprocessing/popen_forkserver.py:47: in _launch
    reduction.dump(process_obj, buf)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

obj = <Process name='Process-9' parent=996 initial>
file = <_io.BytesIO object at 0x7f646bbee390>, protocol = None

    def dump(obj, file, protocol=None):
        '''Replacement for pickle.dump() using ForkingPickler.'''
>       ForkingPickler(file, protocol).dump(obj)
E       _pickle.PicklingError: Can't pickle local object <function TestMultiprocessing.test_redis_client.<locals>.target at 0x7f646bb0f530>
E       when serializing dict item '_target'
E       when serializing multiprocessing.context.Process state
E       when serializing multiprocessing.context.Process object
```

I verified this makes tests pass with Python 3.14.0a2 in Fedora's build environment

2025-03-07 14:59 UTC, petyaslavova requested changes

2025-03-07 14:59 UTC, petyaslavova commented on tests/test_multiprocessing.py
> +
Can you please remove the code on lines 12 and 13, as it also handles a similar issue but for macOS only,  and update your comment to include this case as well?

2025-03-11 12:21 UTC, petyaslavova commented
@befeleme please check linters failure

2025-03-11 12:42 UTC, befeleme commented
Hopefully mitigated.

2025-03-12 09:03 UTC, petyaslavova commented
Hi @befeleme, the linters are failing. You can run them locally to check if there is something else than the one reported from the pipeline, the instructions are available in the [CONTRIBUTING.md](https://github.com/redis/redis-py/blob/master/CONTRIBUTING.md) file

2025-03-12 11:13 UTC, petyaslavova approved these changes

2025-03-12 11:23 UTC, merged