Added Redis 8.0 to test matrix
redis/redis-py pull request #3469
Opened 2024-12-30 10:19 UTC by vladvildanov

### Pull Request check-list

_Please make sure to review and check all of these items:_

- [ ] Do tests and lints pass with this change?
- [ ] Do the CI tests pass with this change (enable it first in your forked repo and wait for the github action build to finish)?
- [ ] Is the new or changed code fully tested?
- [ ] Is a documentation update included (if this change modifies existing APIs, or introduces new ones)?
- [ ] Is there an example added to the examples folder (if applicable)?
- [ ] Was the change added to CHANGES file?

_NOTE: these things are not required to open a PR and can be done
afterwards / while the PR is open._

### Description of change

_Please provide a description of the change here._

2025-01-15 10:09 UTC, uglide requested changes
Some minor changes are required. See my inline comments

2025-01-15 10:09 UTC, uglide commented on tests/test_search.py
> +        assert det[0] == "Shards"
Arguably, we shouldn't test FT.PROFILE reply structure, since we are testing the client here, not the server. I'd suggest trimming most of the checks and replace them with something like 
```python
assert typeof(det) is dict
assert len(det) >= X
```

2025-01-15 10:09 UTC, uglide commented on redis/commands/search/commands.py
> +        if get_protocol_version(self.client) in ["3", 3] and cmd != "FT.PROFILE":
Better to do something like this to hardcode FT.PROFILE only once

```
if get_protocol_version(self.client) in ["3", 3]:
    return ProfileInformation(res) if cmd == "FT.PROFILE" else res
```

2025-01-15 10:14 UTC, uglide reviewed
One more comment

2025-01-15 10:14 UTC, uglide commented on redis/commands/search/commands.py
> -from ..helpers import get_protocol_version, parse_to_dict
It seems that `parse_to_dict` is a dead/unused code now. It should be removed if this is the case with the test case for it.

2025-01-20 09:05 UTC, vladvildanov commented on redis/commands/search/profileInformation.py
Sorry I was mislead by another file `indexDefinition.py`, I will rename both of them

2025-01-21 09:15 UTC, uglide approved these changes
LGTM

2025-01-21 09:24 UTC, merged